package edu.salleurl.g6.model;

public enum TokenType {
    IDENTIFIER, LOGIC_CONSTANT, INTEGER_CONSTANT, STRING, RELATIONAL_OPERATOR, LOGICAL_OPERATOR,
    ARITHMETIC_OPERATOR, SIMPLE_TYPE, KEYWORD, SPECIAL_SYMBOL
}
