package edu.salleurl.g6.model;

public enum TokenType {
    IDENTIFIER,
    LOGIC_CONSTANT,
    INTEGER_CONSTANT,
    STRING,

    OR,
    AND,
    NOT,

    RELATIONAL_OPERATOR,
    SIMPLE_ARITHMETIC_OPERATOR,
    COMPLEX_ARITHMETIC_OPERATOR,

    SIMPLE_TYPE,

    ASSIGNMENT,
    STATEMENT_SEPARATOR, RETURN_TYPE_PREFIX, DECIMAL, ARGUMENT_SEPARATOR, PARENTHESIS_OPEN, PARENTHESIS_CLOSE,
    SQUARE_BRACKETS_OPEN, SQUARE_BRACKETS_CLOSE, BRACKETS_OPEN, BRACKETS_CLOSE, AMPERSAND,


    INICI,
    FI,
    CONST,
    FUNCIO,
    VECTOR,
    DE,
    ESCRIURE,
    LLEGIR,
    REPETIR,
    FINS,
    MENTRE,
    FER,
    FIMENTRE,
    SI,
    LLAVORS,
    SINO,
    FISI,
    RETORNAR,

    EOF
}
